[build]
  # 静的サイトなのでビルドコマンドは不要
  command = ""
  
  # 公開するディレクトリを指定（ルートディレクトリ）
  publish = "."

[build.environment]
  # Node.jsバージョンを指定（必要に応じて）
  NODE_VERSION = "18"

[[headers]]
  # すべてのファイルに適用するヘッダー
  for = "/*"
  [headers.values]
    # キャッシュ制御
    Cache-Control = "public, max-age=31536000"
    # セキュリティヘッダー
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # HTMLファイルのキャッシュを短く設定
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# リダイレクト設定（SPA用、今回は不要だが例として）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404